# Generated by Django 3.2 on 2022-10-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.AutoField(db_column='IdProcessStatus', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=150, null=True)),
            ],
            options={
                'db_table': 'ProcessStatus',
            },
        ),
        migrations.RemoveField(
            model_name='processsteps',
            name='is_done',
        ),
        migrations.AddField(
            model_name='processsteps',
            name='process_steps',
            field=models.ForeignKey(db_column='ProcessSteps', default=1, on_delete=django.db.models.deletion.CASCADE, to='administrators.processstatus'),
            preserve_default=False,
        ),
    ]
