# Generated by Django 3.2 on 2022-11-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_alter_processsteps_calendar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsteps',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
