# Generated by Django 3.2 on 2022-10-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_rename_process_steps_processsteps_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processsteps',
            name='process_status',
            field=models.ForeignKey(db_column='ProcessStatus', on_delete=django.db.models.deletion.CASCADE, to='administrators.processstatus'),
        ),
    ]
