# Generated by Django 3.2 on 2022-11-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_processsteps_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsteps',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
