# Generated by Django 3.2 on 2022-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_processsteps_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsteps',
            name='register_date_time',
            field=models.DateTimeField(blank=True, db_column='RegisterDateTime', null=True),
        ),
    ]
